include $(ROOTDIR)/options.txt

INCLUDEDIR=$(ROOTDIR)/include
SCALARDIR=$(ROOTDIR)/backend/scalar
TENSORDIR=$(ROOTDIR)/backend/tensor
OBJECTSDIR=$(ROOTDIR)/objects
ENGINEDIR=$(ROOTDIR)/engine
TESTSDIR=$(ROOTDIR)/tests

CFLAGS= -std=c++11 -O3 
INCLUDE= -I $(ROOTDIR)/include 
LIBS= -lstdc++ -lm -lpthread 

MACROS=

ifdef WITH_CUDA
MACROS+=-D_WITH_CUDA
endif 

ifdef WITH_CUBLAS
MACROS+=-D_WITH_CUBLAS
endif 

